<a href="https://colab.research.google.com/github/Renju-rl/Git-hub-DSA/blob/main/Dat_Acquisition_Casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Q1

In [203]:
import requests
import sqlite3
import numpy as np
import pandas as pd
url = ' https://api.spacexdata.com/v4/launches'

##Extract relevant columns: name, date_utc, success, details, rocket

In [204]:

response = requests.get(url)
data = response.json()

df_data = pd.DataFrame(data)

df_data = df_data[['name', 'date_utc', 'success', 'details', 'rocket']]

df_data.head()

,name,date_utc,success,details,rocket
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb

##Convert date_utc to datetime and extract the year

In [205]:
df_data['date_utc'] = pd.to_datetime(df_data['date_utc'])
df_data['year'] = df_data['date_utc'].dt.year

df_data.head()

,name,date_utc,success,details,rocket,year
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009

#Q2

##Extract id, name, type, active, and stages

In [206]:
url = 'https://api.spacexdata.com/v4/rockets'
response = requests.get(url)
data2 = response.json()
df_data2 = pd.DataFrame(data2)

df_data2 = df_data2[['id', 'name', 'type', 'active','stages']]
df_data2.head()

                         id          name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

#Q3

##Merge Launch and Rocket Data

*   Join the two DataFrames on rocket ID using

In [207]:
merge_df = pd.DataFrame(df_data.merge(df_data2, left_on="rocket",right_on="id"))
merge_df.head()

,name_x,date_utc,success,details,rocket,year,id,name_y,type,active,stages
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2

#Q4

##Add Simulated Country Information

*   Add a new column country and randomly assign one of these values:
*   ['USA', 'Russia', 'India', 'China', 'France']

In [208]:
countries = ['USA', 'Russia', 'India', 'China', 'France']
merge_df["country"] = np.random.choice(countries, size=len(merge_df))
merge_df

,name_x,date_utc,success,details,rocket,year,id,name_y,type,active,stages,country
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,France
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,Russia
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,France
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,Russia
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,China
...,...,...,...,...,...,...,...,...,...,...,...,...
200,Transporter-6,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2,China
201,TTL-1,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2,USA
202,WorldView Legion 1 & 2,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2,India
203,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022,5e9d0d95eda69974db09d1ed,Falcon Heavy,rocket,True,2,China
204,O3b mPower 3.4,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2,India

#Q5


*  Use sqlite3 to create a connection and save the merged DataFrame as a table named
launches


*   Table should contain all merged columns including country

In [209]:
conn = sqlite3.connect('spacex.db')
merge_df.to_sql('launches', conn, if_exists='replace', index=False)
conn.close()
merge_df

,name_x,date_utc,success,details,rocket,year,id,name_y,type,active,stages,country
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,France
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,Russia
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,France
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,Russia
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,China
...,...,...,...,...,...,...,...,...,...,...,...,...
200,Transporter-6,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2,China
201,TTL-1,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2,USA
202,WorldView Legion 1 & 2,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2,India
203,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022,5e9d0d95eda69974db09d1ed,Falcon Heavy,rocket,True,2,China
204,O3b mPower 3.4,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2,India

#Q6

*   Launches by Country

In [210]:
conn = sqlite3.connect('spacex.db')

query = """
SELECT country, COUNT(*) AS launch_count
FROM launches
GROUP BY country
ORDER BY launch_count DESC;
"""
df_country = pd.read_sql_query(query, conn)
df_country

  country  launch_count
0   China            54
1  Russia            47
2   India            38
3     USA            33
4  France            33

##Which year had the highest number of launches?

In [211]:
query = """
SELECT year, COUNT(*) AS launch_count
FROM launches
GROUP BY year
ORDER BY launch_count DESC
LIMIT 1;
"""
df_top_year = pd.read_sql_query(query, conn)
df_top_year

   year  launch_count
0  2022            62

##  Top 5 Missions by Launch Count

In [214]:
query = """
SELECT name_x, COUNT(*) AS launch_count
FROM launches
GROUP BY name_x
ORDER BY launch_count DESC;
"""

df_top_missions = pd.read_sql_query(query, conn)
df_top_missions.head()

                      name_x  launch_count
0  ispace Mission 1 & Rashid             1
1                       ZUMA             1
2     WorldView Legion 1 & 2             1
3        Viasat-3 & Arcturus             1
4                    USSF-44             1